name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]  # 마스터 브랜치 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest   # GitHub에서 제공하는 Ubuntu 환경에서 실행

    steps:
    - name: Checkout source
      uses: actions/checkout@v3   # 레포 코드 내려받기

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'    # 가장 흔하게 사용하는 오픈 JDK
        java-version: '11'

    - name: Build with sbt
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip
        curl -L -o sbt.zip https://github.com/sbt/sbt/releases/download/v1.10.5/sbt-1.10.5.zip
        unzip sbt.zip -d /opt
        sudo ln -s /opt/sbt/bin/sbt /usr/local/bin/sbt
        sbt clean compile stage

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      run: |
        COMMIT_SHA=${{ github.sha }}
        SHORT_SHA=${COMMIT_SHA::7}

        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tarot-be

        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$SHORT_SHA

    - name: Update image tag in tarot-config repo
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

        SHORT_SHA=${GITHUB_SHA::7}
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/tarot-be

        # tarot-config 레포 클론
        git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/joelonsw/tarot-config.git
        cd tarot-config

        # 이미지 태그 업데이트
        sed -i 's|'"$IMAGE_NAME"':.*|'"$IMAGE_NAME:$SHORT_SHA"'|' k8s/deployment.yaml

        git add k8s/deployment.yaml
        git commit -m "Update image tag to $SHORT_SHA"
        git push origin main
